"""'add_contacts'

Revision ID: dd30b6b79f4d
Revises: ea8e27d3f570
Create Date: 2021-12-06 20:45:54.617863

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dd30b6b79f4d'
down_revision = 'ea8e27d3f570'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('contacts',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('owner_id', sa.Integer(), nullable=True),
    sa.Column('client_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['client_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('users', sa.Column('password', sa.String(), nullable=False))
    op.alter_column('users', 'login',
               existing_type=sa.VARCHAR(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'login',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.drop_column('users', 'password')
    op.drop_table('contacts')
    # ### end Alembic commands ###
